-- Deploy pgtapme_dev:tables/d_date_rule to pg
-- requires: appschema

BEGIN;

CREATE TABLE pgtapme.d_date_rule (
    fk int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Date" text NOT NULL,
    "Full Date Description" text NOT NULL,
    "Day of Week" text NOT NULL,
    "Short Day of Week" text NOT NULL,
    "Day Number in Month" int4 NOT NULL,
    "Day Number in Year" int4 NOT NULL,
    "Last Day in Week Indicator" text NOT NULL,
    "Last Day in Month Indicator" text NOT NULL,
    "Week Ending Date" text NOT NULL,
    "Week Number in Year" int4 NOT NULL,
    "Week Number in Month" int4 NOT NULL,
    "Month Name" text NOT NULL,
    "Short Month Name" text NOT NULL,
    "Month Number in Year" int4 NOT NULL,
    "Year-Month" text NOT NULL,
    "Year Quarter" text NOT NULL,
    "Year-Quarter" text NOT NULL,
    "Year Half" text NOT NULL,
    "Year" text NOT NULL,
    "Weekday Indicator" text NOT NULL,
    "Year-Half" text NOT NULL,
    "SQL Date" date NOT NULL,
    CONSTRAINT d_date_rule_dow_chk CHECK (("Day of Week" = ANY ('{Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday}'::text[]))),
    CONSTRAINT d_date_rule_dow_short_chk CHECK (("Short Day of Week" = ANY ('{Mon,Tue,Wed,Thu,Fri,Sat,Sun}'::text[]))),
    CONSTRAINT d_date_rule_mth_chk CHECK (("Month Name" = ANY ('{January,February,March,April,May,June,July,August,September,October,November,December}'::text[]))),
    CONSTRAINT d_date_rule_mth_short_chk CHECK (("Short Month Name" = ANY ('{Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec}'::text[]))),
    CONSTRAINT d_date_rule_pk PRIMARY KEY ("SQL Date")
);

COMMIT;
