-- Deploy pgtapme_dev:tables/d_date_declarative to pg
-- requires: appschema
-- requires: tables/d_date_with_exclusion_constraint
-- requires: data/d_date_exclusion_populate

BEGIN;

CREATE TABLE pgtapme.d_date_declarative (
  fk int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Date" text NOT NULL,
  "Full Date Description" text NULL,
  "Day of Week" text NULL,
  "Short Day of Week" text NULL,
  "Day Number in Month" int4 NULL,
  "Day Number in Year" int4 NULL,
  "Last Day in Week Indicator" text NULL,
  "Last Day in Month Indicator" text NULL,
  "Week Ending Date" text NULL,
  "Week Number in Year" int4 NULL,
  "Week Number in Month" int4 NULL,
  "Month Name" text NULL,
  "Short Month Name" text NULL,
  "Month Number in Year" int4 NULL,
  "Year-Month" text NULL,
  "Year Quarter" text NULL,
  "Year-Quarter" text NULL,
  "Year Half" text NULL,
  "Year" text NULL,
  "Weekday Indicator" text NULL,
  "Year-Half" text NULL,
  "SQL Date" date NOT NULL,
  CONSTRAINT d_date_declarative_dow_chk CHECK (("Day of Week" = ANY ('{Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday}'::text[]))),
  CONSTRAINT d_date_declarative_dow_short_chk CHECK (("Short Day of Week" = ANY ('{Mon,Tue,Wed,Thu,Fri,Sat,Sun}'::text[]))),
  CONSTRAINT d_date_declarative_mth_chk CHECK (("Month Name" = ANY ('{January,February,March,April,May,June,July,August,September,October,November,December}'::text[]))),
  CONSTRAINT d_date_declarative_mth_short_chk CHECK (("Short Month Name" = ANY ('{Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec}'::text[]))),
  CONSTRAINT d_date_declarative_pk PRIMARY KEY ("SQL Date")
) PARTITION BY RANGE ( "SQL Date" );

COMMIT;
