-- Deploy pgtapme_dev:tables/d_date_with_exclusion_constraint to pg
-- requires: appschema
-- requires: tables/lkp_dow
-- requires: tables/lkp_mth
-- requires: extschema
-- requires: gist_ext

BEGIN;

CREATE TABLE pgtapme.d_date_exclusion (
  fk bigint CONSTRAINT d_date_exclusion_fk_uidx UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Date" text NOT NULL CONSTRAINT d_date_exclusion_date_uix UNIQUE,
  "Full Date Description" text NOT NULL,
  "Day of Week" text NOT NULL CONSTRAINT d_date_exclusion_lkp_dow_long_name_ic_fk REFERENCES pgtapme.lkp_dow (long_name_ic) DEFERRABLE INITIALLY IMMEDIATE,
  "Short Day of Week" text NOT NULL CONSTRAINT d_date_exclusion_lkp_dow_short_name_ic_fk REFERENCES pgtapme.lkp_dow (short_name_ic) DEFERRABLE INITIALLY IMMEDIATE,
  "Day Number in Month" int4 NOT NULL,
  "Day Number in Year" int4 NOT NULL,
  "Last Day in Week Indicator" text NOT NULL,
  "Last Day in Month Indicator" text NOT NULL,
  "Week Ending Date" text NOT NULL,
  "Week Number in Year" int4 NOT NULL,
  "Week Number in Month" int4 NOT NULL,
  "Month Name" text NOT NULL CONSTRAINT d_date_exclusion_lkp_mth_long_name_ic_fk REFERENCES pgtapme.lkp_mth (long_name_ic) DEFERRABLE INITIALLY IMMEDIATE,
  "Short Month Name" text NOT NULL CONSTRAINT d_date_exclusion_lkp_mth_short_name_ic_fk REFERENCES pgtapme.lkp_mth (short_name_ic) DEFERRABLE INITIALLY IMMEDIATE,
  "Month Number in Year" int4 NOT NULL,
  "Year-Month" text NOT NULL,
  "Year Quarter" text NOT NULL,
  "Year-Quarter" text NOT NULL,
  "Year Half" text NOT NULL,
  "Year" text NOT NULL,
  "Weekday Indicator" text NOT NULL,
  "Year-Half" text NOT NULL,
  "SQL Date" date NOT NULL CONSTRAINT d_date_exclusion_pk PRIMARY KEY,
  CONSTRAINT d_date_exclusion_exclusion_chk EXCLUDE USING gist ("SQL Date" WITH =, pgtapme.date_range('1 jan 0001'::DATE, '31 dec 30001'::DATE) WITH &&)
);

COMMIT;
