services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development # Use the 'development' stage from the Dockerfile for devcontainer setup
    volumes:
      - ./code:/home/vscode/code # Mount the code directory for immediate updates in development
    user: vscode
    environment:
      - PYTHONUNBUFFERED=1 # Ensure the output is not buffered, useful for logging
    depends_on:
      - manager_db
      - pgtapme_db
      - dvdrental_db
      - dvdrental_alt_db
    command: [ "tail", "-f", "/dev/null" ] # Keeps the container running for devcontainer usage

  manager_db:
    build:
      context: ./db/manager
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./db/manager/conf.d:/etc/postgresql/conf.d

  pgtapme_db:
    build:
      context: ./db/pgtapme
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgtapme/conf.d:/etc/postgresql/conf.d

  dvdrental_alt_db:
    build:
      context: ./db/dvdrental_alt
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/dvdrental_alt/conf.d:/etc/postgresql/conf.d

  dvdrental_db:
    build:
      context: ./db/dvdrental
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./db/dvdrental/conf.d:/etc/postgresql/conf.d

  sqitch:
    image: sqitch/sqitch
    user: sqitch
    volumes:
      - ./sqitch/.sqitch/sqitch.conf:/home/.sqitch/sqitch.conf
      - ./sqitch/.sqitch/.pgpass:/home/.pgpass:ro
      - ./sqitch/sqitch.sh:/home/sqitch.sh
      - ./sqitch/sqitch.conf:/mnt/sqitch/sqitch.conf
      - ./sqitch/projects/:/mnt/sqitch/
    working_dir: /mnt/sqitch
    entrypoint: /bin/bash
    command: -c "tail -f /dev/null"
    depends_on:
      - manager_db
      - pgtapme_db
      - dvdrental_db
      - dvdrental_alt_db

  pg_prove:
    image: itheory/pg_prove
    volumes:
      - ./code/pgtapme_generated_files:/mnt/tests
      - ./pg_prove/pg_prove.sh:/mnt/pg_prove/pg_prove.sh
      - ./pg_prove/projects/:/mnt/tests/
    environment:
      PGPASSWORD: mysecretpassword
    entrypoint: /bin/sh
    command: -c "tail -f /dev/null"
    depends_on:
      - manager_db
      - pgtapme_db
      - dvdrental_db
      - dvdrental_alt_db
