services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development # Use the 'development' stage from the Dockerfile for devcontainer setup
    volumes:
      - ./code:/home/vscode/code # Mount the code directory for immediate updates in development
    user: vscode
    environment:
      - PYTHONUNBUFFERED=1 # Ensure the output is not buffered, useful for logging
    depends_on:
      pgtapme_db:
        condition: service_healthy
      fdw_source:
        condition: service_healthy
    command: [ "tail", "-f", "/dev/null" ] # Keeps the container running for devcontainer usage

  pgtapme_db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGTAPME_DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/conf.d:/etc/postgresql/conf.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 5s

  fdw_source:
    build:
      context: ./db/fdw_source
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGTAPME_DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: postgres
    user: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 5s

  sqitch:
    image: sqitch/sqitch
    user: sqitch
    environment:
      PGPASSWORD: ${PGTAPME_DB_PASSWORD:-mysecretpassword}
    volumes:
      - ./sqitch/.sqitch/sqitch.conf:/home/.sqitch/sqitch.conf
      - ./.pgpass:/home/.pgpass:ro
      - ./sqitch/sqitch.sh:/home/sqitch.sh
      - ./sqitch/migrations/:/mnt/migrations/
      - ./sqitch/migrations/sqitch.conf:/mnt/migrations/sqitch.conf
    working_dir: /mnt/migrations
    entrypoint: /bin/bash
    command: -c "tail -f /dev/null"
    depends_on:
      pgtapme_db:
        condition: service_healthy
      fdw_source:
        condition: service_healthy

  sqitch_fdw_source:
    image: sqitch/sqitch
    user: sqitch
    environment:
      PGPASSWORD: ${PGTAPME_DB_PASSWORD:-mysecretpassword}
    volumes:
      - ./sqitch/.sqitch/sqitch.conf:/home/.sqitch/sqitch.conf
      - ./.pgpass:/home/.pgpass:ro
      - ./sqitch/projects/fdw_source/:/mnt/migrations/
    working_dir: /mnt/migrations
    entrypoint: /bin/bash
    command: -c "tail -f /dev/null"
    depends_on:
      fdw_source:
        condition: service_healthy

  pg_prove:
    image: itheory/pg_prove
    volumes:
      - ./code/pgtapme_generated_files:/mnt/tests
      - ./pg_prove/pg_prove.sh:/mnt/pg_prove/pg_prove.sh
    environment:
      PGPASSWORD: mysecretpassword
    entrypoint: /bin/sh
    command: -c "tail -f /dev/null"
    depends_on:
      pgtapme_db:
        condition: service_healthy
      fdw_source:
        condition: service_healthy
