services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
    depends_on:
      - db
      - sqitch
      - pg_prove

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sqitch:
    image: sqitch/sqitch
    volumes:
      - ./sqitch:/mnt/sqitch
    working_dir: /mnt/sqitch
    entrypoint: /bin/sh
    command: -c "tail -f /mnt/sqitch/sqitch.plan"
    depends_on:
      - db

  pg_prove:
    image: itheory/pg_prove
    volumes:
      - ./code/pgtapme_generated_files:/mnt/tests
      - ./pg_prove:/mnt/pg_prove
    environment:
      PGPASSWORD: mysecretpassword
    entrypoint: /bin/sh
    command: -c "tail -f /mnt/pg_prove/pg_prove.sh"
    depends_on:
      - db
      - sqitch

volumes:
  postgres_data:
