services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sqitch:
    image: sqitch/sqitch
    user: sqitch
    volumes:
      - ./sqitch/.sqitch/sqitch.conf:/home/.sqitch/sqitch.conf
      - ./sqitch/sqitch.sh:/home/sqitch.sh
      - ./sqitch/dvdrental:/mnt/sqitch/dvdrental
      - ./sqitch/pgtapme:/mnt/sqitch/pgtapme
      - ./sqitch/sqitch.conf:/mnt/sqitch/sqitch.conf
      - ./sqitch/.sqitch/.pgpass:/home/.pgpass:ro
      - ./sqitch/entrypoint.sh:/mnt/sqitch/entrypoint.sh
    working_dir: /mnt/sqitch
    command: -c "tail -f /home/sqitch.sh"
    depends_on:
      - db

  pg_prove:
    image: itheory/pg_prove
    volumes:
      - ./code/pgtapme_generated_files:/mnt/tests
      - ./pg_prove:/mnt/pg_prove
    environment:
      PGPASSWORD: mysecretpassword
    entrypoint: /bin/sh
    command: -c "tail -f /mnt/pg_prove/pg_prove.sh"
    depends_on:
      - db

volumes:
  postgres_data:
