name: CI for pgtapme.py Development using Docker Compose

on: [push]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start docker-compose Containers
      run: |
        docker-compose up --build -d

    - name: Check Database is Ready
      run: |
        if ! docker inspect --format='{{json .State.Status}}' $(docker-compose ps -q db) | grep -q "running"; then
          echo "Database is not ready"
          exit 1
        fi

    - name: Check App is Ready
      run: |
        if ! docker inspect --format='{{json .State.Status}}' $(docker-compose ps -q app) | grep -q "running"; then
          echo "App is not ready"
          exit 1
        fi

    - name: Check Sqitch is Ready
      run: |
        if ! docker inspect --format='{{json .State.Status}}' $(docker-compose ps -q sqitch) | grep -q "running"; then
          echo "Sqitch is not ready"
          exit 1
        fi

    - name: Check Pg_prove is Ready
      run: |
        if ! docker inspect --format='{{json .State.Status}}' $(docker-compose ps -q pg_prove) | grep -q "running"; then
          echo "Pg_prove is not ready"
          exit 1
        fi

    - name: Deploy Database with Sqitch
      run: |
        docker-compose exec -T sqitch env PGUSER=dbo PGPASSWORD=mysecretpassword sqitch deploy --target dvdrental

    - name: Generate Database Tests with PGtapme (--db-name dvdrental)
      run: |
        docker-compose exec -T app python /code/pgtapme.py --db-name dvdrental

    - name: Run PGTap Tests with PgProve (dvdrental)
      run: |
        docker-compose exec -T pg_prove pg_prove -r --ext .sql -p 5432 -h db -U dbo -d dvdrental -f /mnt/tests/dvdrental

    - name: Verify Database with Sqitch
      run: |
        docker-compose exec -T sqitch env PGUSER=dbo PGPASSWORD=mysecretpassword sqitch verify --target dvdrental

    - name: Revert Database with Sqitch
      run: |
        docker-compose exec -T sqitch env PGUSER=dbo PGPASSWORD=mysecretpassword sqitch revert --target dvdrental -y

    # - name: Run PGTap Tests with PgProve (dvdrental)
    #   run: |
    #     docker-compose exec -T pg_prove pg_prove -r --ext .sql -p 5432 -h db -U dbo -d dvdrental -f /mnt/tests/dvdrental

    - name: Shutdown Docker Compose
      if: always()
      run: |
        docker-compose -f docker-compose.yml down

    # - name: Upload Test Results
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-results
    #     path: code/pgtapme_generated_files/dvdrental_results.txt
